// <auto-generated />
using System;
using BookStoreWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreWeb.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b1764-de89-7041-9480-e929bce37644"),
                            CreatedAt = new DateTime(2025, 12, 13, 11, 7, 25, 193, DateTimeKind.Utc).AddTicks(6483),
                            DisplayOrder = 1,
                            Name = "Action",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b1764-de89-7e46-83f2-b22fabd14427"),
                            CreatedAt = new DateTime(2025, 12, 13, 11, 7, 25, 193, DateTimeKind.Utc).AddTicks(6886),
                            DisplayOrder = 2,
                            Name = "Sci-fi",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b1764-de89-72f4-8f68-2cc968d1cdb2"),
                            CreatedAt = new DateTime(2025, 12, 13, 11, 7, 25, 193, DateTimeKind.Utc).AddTicks(6888),
                            DisplayOrder = 3,
                            Name = "History",
                            RecordState = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
