// <auto-generated />
using System;
using BookStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215082645_AddCategoriesAndSeed")]
    partial class AddCategoriesAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b211e-7d79-725c-b250-47d2dc3f9079"),
                            CreatedAt = new DateTime(2025, 12, 15, 8, 26, 44, 985, DateTimeKind.Utc).AddTicks(917),
                            DisplayOrder = 1,
                            Name = "Action",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b211e-7d79-743b-ba1b-67c50cd3e00d"),
                            CreatedAt = new DateTime(2025, 12, 15, 8, 26, 44, 985, DateTimeKind.Utc).AddTicks(1370),
                            DisplayOrder = 2,
                            Name = "Sci-fi",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b211e-7d79-7fc3-bbf8-1b8b29f3fce5"),
                            CreatedAt = new DateTime(2025, 12, 15, 8, 26, 44, 985, DateTimeKind.Utc).AddTicks(1372),
                            DisplayOrder = 3,
                            Name = "History",
                            RecordState = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
