// <auto-generated />
using System;
using BookStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b27c4-40b0-70c7-8762-3ff661b5ac90"),
                            CreatedAt = new DateTime(2025, 12, 16, 15, 25, 31, 696, DateTimeKind.Utc).AddTicks(4911),
                            DisplayOrder = 1,
                            Name = "Action",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b27c4-40b0-77a2-b4f5-85bf2ccc57d3"),
                            CreatedAt = new DateTime(2025, 12, 16, 15, 25, 31, 696, DateTimeKind.Utc).AddTicks(5315),
                            DisplayOrder = 2,
                            Name = "Sci-fi",
                            RecordState = "Active"
                        },
                        new
                        {
                            Id = new Guid("019b27c4-40b0-73ef-b033-4f48ee3c444f"),
                            CreatedAt = new DateTime(2025, 12, 16, 15, 25, 31, 696, DateTimeKind.Utc).AddTicks(5317),
                            DisplayOrder = 3,
                            Name = "History",
                            RecordState = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
